package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"net/http"
	"strings"

	"github.com/gin-gonic/gin"
)

type Send struct {
	URL    string          `json:"url"`
	Header http.Header     `json:"header"`
	Body   string          `json:"body"`
	Raw    json.RawMessage `json:"raw"`
}

func Login(c *gin.Context) {
	//req := make(map[string]interface{}) //注意该结构接受的内容
	//c.BindJSON(&req)
	//log.Printf("%v", req)
	body, _ := ioutil.ReadAll(c.Request.Body)
	hit := false
	for k, v := range c.Request.Header {
		if k == "Content-Type" {
			for _, vv := range v {
				if strings.Contains(vv, "application/json") {
					hit = true
				}
			}
		}
	}
	//c.request.host+c.request.url.path
	req := Send{
		URL:    c.Request.URL.String(),
		Header: c.Request.Header,
	}
	if hit {
		req.Raw = body
	} else {
		req.Body = string(body)
	}
	out1, _ := json.Marshal(req)
	httpPost(string(out1))
	c.JSON(http.StatusOK, gin.H{})
}
func main() {
	r := gin.Default()
	//r.POST("/", func(c *gin.Context) {
	//	c.JSON(200, gin.H{
	//		"message": "pong",
	//	})
	//})
	r.POST("/", Login)
	// listen and serve on 0.0.0.0:8080 (for windows "localhost:8080")
	r.Run()
}

type AutoGenerated struct {
	Msgtype string `json:"msgtype"`
	Text    `json:"text"`
}
type Text struct {
	Content string `json:"content"`
}

func httpPost(data string) {
	uri := "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=f841984f-3115-49f4-b264-c567e31dbde9"
	ag := AutoGenerated{
		Msgtype: "text",
		Text:    Text{Content: data},
	}
	str, _ := json.Marshal(ag)
	resp, err := http.Post(uri, "Content-Type: application/json", bytes.NewReader(str))
	if err != nil {
		fmt.Println(err)
	}

	defer resp.Body.Close()
	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(string(body))
}
